<a href="https://colab.research.google.com/github/Dr-Ning-An/FEM_Course/blob/main/POD_Example/SVD_POD_reduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from scipy.linalg import svd

# Define input data matrix X
X = np.array([
    [1, 5, 3, 3],
    [1, 4, 4, 3],
    [1, 5, 5, 4]
], dtype=float)

# Display the original data matrix
print("Original Data Matrix:\n", X)

Original Data Matrix:
 [[1. 5. 3. 3.]
 [1. 4. 4. 3.]
 [1. 5. 5. 4.]]


In [2]:
# Perform Singular Value Decomposition (SVD) on the data matrix
U, S, VT = svd(X)

# Calculate the POD basis (U matrix from SVD)
pod_basis = U
print("\nPOD Basis / Left Singular Vectors:\n", pod_basis)

print("\nSingular Values:\n",S)

print("\nTranspose of Right Singular Vectors:\n",VT)


POD Basis / Left Singular Vectors:
 [[ 0.53248416  0.84624208  0.01830206]
 [ 0.52545445 -0.31352754 -0.7909476 ]
 [ 0.66359494 -0.43078397  0.61161011]]

Singular Values:
 [12.30834838  1.20802645  0.21267859]

Transpose of Right Singular Vectors:
 [[ 0.13986714  0.65664483  0.57012076  0.47351565]
 [ 0.08437777  0.68142582 -0.71960655 -0.10346813]
 [-0.75717737 -0.06690608 -0.23901616  0.60421625]
 [ 0.63245553 -0.31622777 -0.31622777  0.63245553]]


In [3]:
# Calculate energy content of each singular value
energy_content = (S**2) / np.sum(S**2)

# Calculate the cumulative energy content
cumulative_energy = np.cumsum(energy_content)

# Determine the number of POD basis vectors needed to achieve the desired error
desired_error = 0.001
num_basis_vectors = np.sum(cumulative_energy < (1 - desired_error)) + 1

# Truncate the POD basis
truncated_pod_basis = U[:, :num_basis_vectors]
print(f"\nTruncated POD Basis (using {num_basis_vectors} vectors):\n", truncated_pod_basis)


Truncated POD Basis (using 2 vectors):
 [[ 0.53248416  0.84624208]
 [ 0.52545445 -0.31352754]
 [ 0.66359494 -0.43078397]]


In [4]:
# Calculate the reduced matrix using the truncated POD basis
reduced_matrix = truncated_pod_basis.T @ X
print("\nReduced Matrix:\n", reduced_matrix)

# Reconstruct the original matrix from the reduced matrix
reconstructed_matrix = truncated_pod_basis @ reduced_matrix
print("\nReconstructed Matrix:\n", reconstructed_matrix)

# Calculate the reconstruction error
error = np.linalg.norm(X - reconstructed_matrix)
print(f"\nReconstruction Error: {error}")


Reduced Matrix:
 [[ 1.72153355  8.08221328  7.01724497  5.82819558]
 [ 0.10193057  0.82318041 -0.86930375 -0.12499224]]

Reconstructed Matrix:
 [[1.00294728 5.00026043 3.00093036 2.99764811]
 [0.87262942 3.98874522 3.95979327 3.10163982]
 [1.09849089 5.0087029  5.03109036 3.92140574]]

Reconstruction Error: 0.2126785923857775
